[build-system]
requires = ["setuptools>=45", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "vhdl_extras"
version = "1.0.0"
description = "vhdl-extras packaged for tsfpga and with VHDL components declaration."
readme = "README.rst"
requires-python = ">=3.9"
license = {file = "COPYING"}
dependencies = ["tsfpga"]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages]
find = {include = ["vhdl_extras*"]}

[tool.setuptools.package-data]
"*" = ["*.vhd", "*.tcl", "*.vhdl"]
